package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"agentdock/internal/config"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

var (
	initConfigPath  string
	initForce       bool
	initInteractive bool
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Generate a starter config file",
	Long:  "Writes a starter config to the path specified by --config (default ~/.config/agentdock/config.yaml).",
	RunE: func(cmd *cobra.Command, args []string) error {
		path, err := resolveConfigPath(initConfigPath)
		if err != nil {
			return err
		}
		return runInit(path, initInteractive, initForce)
	},
}

func init() {
	initCmd.Flags().StringVarP(&initConfigPath, "config", "c", "", "path for new config file (default ~/.config/agentdock/config.yaml)")
	initCmd.Flags().BoolVar(&initForce, "force", false, "overwrite if file exists")
	initCmd.Flags().BoolVarP(&initInteractive, "interactive", "i", false, "prompt for required values")
	rootCmd.AddCommand(initCmd)
}

// runInit creates the starter config file at path. Format chosen by extension
// (.yaml/.yml → YAML w/ comments; .json → JSON; otherwise → YAML).
// If interactive, runs prompts for required secrets first.
func runInit(path string, interactive, force bool) error {
	if _, err := os.Stat(path); err == nil && !force {
		return fmt.Errorf("config already exists at %s; pass --force to overwrite", path)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}

	var cfg config.Config
	data, _ := yaml.Marshal(config.DefaultsMap())
	yaml.Unmarshal(data, &cfg)
	cfg.Agents = map[string]config.AgentConfig{}
	for k, v := range config.BuiltinAgents {
		cfg.Agents[k] = v
	}

	prompted := map[string]any{}
	if interactive {
		if err := initPromptAll(&cfg, prompted); err != nil {
			return err
		}
	}

	var out []byte
	switch strings.ToLower(filepath.Ext(path)) {
	case ".json":
		b, err := json.MarshalIndent(&cfg, "", "  ")
		if err != nil {
			return fmt.Errorf("marshal json: %w", err)
		}
		out = b
	default:
		b, err := marshalYAMLWithComments(&cfg)
		if err != nil {
			return fmt.Errorf("marshal yaml: %w", err)
		}
		out = b
	}

	return atomicWrite(path, out, 0600)
}

// marshalYAMLWithComments serializes cfg to YAML and inserts # REQUIRED markers
// for slack/github/redis blocks if their key fields are empty.
func marshalYAMLWithComments(cfg *config.Config) ([]byte, error) {
	raw, err := yaml.Marshal(cfg)
	if err != nil {
		return nil, err
	}
	text := string(raw)

	insertBefore := func(s, anchor, comment string) string {
		if strings.Contains(s, anchor) {
			return strings.Replace(s, anchor, comment+"\n"+anchor, 1)
		}
		return s
	}
	if cfg.Slack.BotToken == "" {
		text = insertBefore(text, "slack:", "# REQUIRED for `agentdock app`: Slack bot+app tokens")
	}
	if cfg.GitHub.Token == "" {
		text = insertBefore(text, "github:", "# REQUIRED for both subcommands: GitHub token")
	}
	if cfg.Redis.Addr == "" {
		text = insertBefore(text, "redis:", "# REQUIRED for both subcommands: Redis address")
	}
	text = "# Generated by `agentdock init`. See agentdock --help for flag overrides.\n" + text
	return []byte(text), nil
}

func atomicWrite(path string, data []byte, mode os.FileMode) error {
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, mode); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

// initPromptAll runs the 5 prompts (Slack bot, Slack app, GitHub, Redis, Providers).
// Implemented in Task 19; for Task 18 stub returns error.
func initPromptAll(cfg *config.Config, prompted map[string]any) error {
	return fmt.Errorf("init -i not yet implemented; coming in next task")
}
