package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"syscall"

	"github.com/Ivantseng123/agentdock/internal/config"
	"github.com/Ivantseng123/agentdock/shared/configloader"
	"github.com/Ivantseng123/agentdock/shared/connectivity"

	"github.com/spf13/cobra"
	"golang.org/x/term"
	"gopkg.in/yaml.v3"
)

var (
	initConfigPath  string
	initForce       bool
	initInteractive bool
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Generate a starter config file",
	Long:  "Writes a starter config to the path specified by --config (default ~/.config/agentdock/config.yaml).",
	RunE: func(cmd *cobra.Command, args []string) error {
		path, err := resolveConfigPath(initConfigPath)
		if err != nil {
			return err
		}
		return runInit(path, initInteractive, initForce)
	},
}

func init() {
	initCmd.Flags().StringVarP(&initConfigPath, "config", "c", "", "path for new config file (default ~/.config/agentdock/config.yaml)")
	initCmd.Flags().BoolVar(&initForce, "force", false, "overwrite if file exists")
	initCmd.Flags().BoolVarP(&initInteractive, "interactive", "i", false, "prompt for required values")
	rootCmd.AddCommand(initCmd)
}

// runInit creates the starter config file at path. Format chosen by extension
// (.yaml/.yml → YAML w/ comments; .json → JSON; otherwise → YAML).
// If interactive, runs prompts for required secrets first.
func runInit(path string, interactive, force bool) error {
	if interactive && !term.IsTerminal(int(syscall.Stdin)) {
		return fmt.Errorf("--interactive requires a terminal (stdin is not a TTY)")
	}
	if _, err := os.Stat(path); err == nil && !force {
		return fmt.Errorf("config already exists at %s; pass --force to overwrite", path)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}

	var cfg config.Config
	data, _ := yaml.Marshal(config.DefaultsMap())
	yaml.Unmarshal(data, &cfg)
	cfg.Agents = map[string]config.AgentConfig{}
	for k, v := range config.BuiltinAgents {
		cfg.Agents[k] = v
	}

	prompted := map[string]any{}
	if interactive {
		if err := initPromptAll(&cfg, prompted); err != nil {
			return err
		}
	}

	var out []byte
	switch strings.ToLower(filepath.Ext(path)) {
	case ".json":
		b, err := json.MarshalIndent(&cfg, "", "  ")
		if err != nil {
			return fmt.Errorf("marshal json: %w", err)
		}
		out = b
	default:
		b, err := marshalYAMLWithComments(&cfg)
		if err != nil {
			return fmt.Errorf("marshal yaml: %w", err)
		}
		out = b
	}

	return atomicWrite(path, out, 0600)
}

// atomicWrite is retained as a thin wrapper so existing tests keep their
// short name. Pure logic lives in shared/configloader.AtomicWrite.
func atomicWrite(path string, data []byte, mode os.FileMode) error {
	return configloader.AtomicWrite(path, data, mode)
}

// marshalYAMLWithComments serializes cfg to YAML and inserts # REQUIRED markers
// for slack/github/redis blocks if their key fields are empty.
func marshalYAMLWithComments(cfg *config.Config) ([]byte, error) {
	raw, err := yaml.Marshal(cfg)
	if err != nil {
		return nil, err
	}
	text := string(raw)

	insertBefore := func(s, anchor, comment string) string {
		if strings.Contains(s, anchor) {
			return strings.Replace(s, anchor, comment+"\n"+anchor, 1)
		}
		return s
	}
	if cfg.Slack.BotToken == "" {
		text = insertBefore(text, "slack:", "# REQUIRED for `agentdock app`: Slack bot+app tokens")
	}
	if cfg.GitHub.Token == "" {
		text = insertBefore(text, "github:", "# REQUIRED for both subcommands: GitHub token")
	}
	if cfg.Redis.Addr == "" {
		text = insertBefore(text, "redis:", "# REQUIRED for both subcommands: Redis address")
	}
	text = "# Generated by `agentdock init`. See agentdock --help for flag overrides.\n" + text
	return []byte(text), nil
}

// initPromptAll runs the 5 prompts (Slack bot, Slack app, GitHub, Redis, Providers).
func initPromptAll(cfg *config.Config, prompted map[string]any) error {
	fmt.Fprintln(stderr)

	// Slack bot token
	fmt.Fprintln(stderr, "  Slack bot token (xoxb-...):")
	for attempt := 1; attempt <= maxRetries; attempt++ {
		token := promptHidden("Token: ")
		if token == "" {
			printFail("Slack bot token is required")
			if attempt == maxRetries {
				return fmt.Errorf("max retries exceeded for Slack bot token")
			}
			continue
		}
		userID, err := connectivity.CheckSlackToken(token)
		if err != nil {
			printFail("%v (attempt %d/%d)", err, attempt, maxRetries)
			if attempt == maxRetries {
				return fmt.Errorf("max retries exceeded for Slack bot token")
			}
			continue
		}
		cfg.Slack.BotToken = token
		prompted["slack.bot_token"] = token
		printOK("Slack bot token valid (user_id: %s)", userID)
		break
	}

	// Slack app token
	fmt.Fprintln(stderr)
	fmt.Fprintln(stderr, "  Slack app-level token (xapp-...):")
	for attempt := 1; attempt <= maxRetries; attempt++ {
		token := promptHidden("Token: ")
		if token == "" || !strings.HasPrefix(token, "xapp-") {
			printFail("must start with xapp- (attempt %d/%d)", attempt, maxRetries)
			if attempt == maxRetries {
				return fmt.Errorf("max retries exceeded for Slack app token")
			}
			continue
		}
		cfg.Slack.AppToken = token
		prompted["slack.app_token"] = token
		printOK("Slack app token format OK")
		break
	}

	// GitHub token
	fmt.Fprintln(stderr)
	fmt.Fprintln(stderr, "  GitHub token (ghp_... or github_pat_...):")
	fmt.Fprintln(stderr, "  Generate at: https://github.com/settings/tokens")
	for attempt := 1; attempt <= maxRetries; attempt++ {
		token := promptHidden("Token: ")
		if token == "" {
			printFail("GitHub token is required")
			if attempt == maxRetries {
				return fmt.Errorf("max retries exceeded for GitHub token")
			}
			continue
		}
		username, err := connectivity.CheckGitHubToken(token)
		if err != nil {
			printFail("%v (attempt %d/%d)", err, attempt, maxRetries)
			if attempt == maxRetries {
				return fmt.Errorf("max retries exceeded for GitHub token")
			}
			continue
		}
		cfg.GitHub.Token = token
		prompted["github.token"] = token
		printOK("GitHub token valid (user: %s)", username)
		break
	}

	// Redis address
	fmt.Fprintln(stderr)
	for attempt := 1; attempt <= maxRetries; attempt++ {
		addr := promptLine("Redis address: ")
		if addr == "" {
			printFail("Redis address is required")
			if attempt == maxRetries {
				return fmt.Errorf("max retries exceeded for Redis address")
			}
			continue
		}
		if err := connectivity.CheckRedis(addr, "", 0, false); err != nil {
			printFail("Redis connect failed: %v (attempt %d/%d)", err, attempt, maxRetries)
			if attempt == maxRetries {
				return fmt.Errorf("max retries exceeded for Redis")
			}
			continue
		}
		cfg.Redis.Addr = addr
		prompted["redis.addr"] = addr
		printOK("Redis connected")
		break
	}

	// Providers
	fmt.Fprintln(stderr)
	agents := sortedAgentNames(cfg)
	fmt.Fprintln(stderr, "  Available providers:")
	for i, name := range agents {
		fmt.Fprintf(stderr, "    %d) %s\n", i+1, name)
	}
	for attempt := 1; attempt <= maxRetries; attempt++ {
		input := promptLine("Select (comma-separated, e.g. 1,2): ")
		selected := parseSelection(input, agents)
		if len(selected) == 0 {
			printFail("At least one provider is required (attempt %d/%d)", attempt, maxRetries)
			if attempt == maxRetries {
				return fmt.Errorf("max retries exceeded for providers")
			}
			continue
		}
		cfg.Providers = selected
		prompted["providers"] = selected
		break
	}

	return nil
}
